const fetch = require('node-fetch'); 

let getAllRadicals = () => {
    return radicals.map(data => data.radical);
};

function getRadicalNum(current) {
  for (const data of radicals) {
      if (current === data.radical) {
          return data.number;
      }
  }
}

//this checks if the inputted chara actually uses the radical
function checksRadicals(userInput, allCharasWithRadical) {
  return allCharasWithRadical.includes(userInput);
}

//gets all the characters associated with the radical
async function fetchCharacters(currentNum) {
  try {
      const radicalListRandom = await fetch(`http://ccdb.hemiola.com/characters/radicals/${currentNum}`);
      const radicalResult = await radicalListRandom.json();

      return radicalResult.map(data => data.string);

    } catch (error) {
      console.error('Error', error);
  }
}


//array of js objects that include the radical
//and its associated number
const radicals = [
    { number: 1, radical: '一' },
    { number: 2, radical: '丨' },
    { number: 3, radical: '丶' },
    { number: 4, radical: '丿 乀 乁' },
    { number: 5, radical: '乙 乚' },
    { number: 6, radical: '亅' },
    { number: 7, radical: '二' },
    { number: 8, radical: '亠' },
    { number: 9, radical: '人 亻' },
    { number: 10, radical: '儿' },
    { number: 11, radical: '入' },
    { number: 12, radical: '八 丷' },
    { number: 13, radical: '冂' },
    { number: 14, radical: '冖' },
    { number: 15, radical: '冫' },
    { number: 16, radical: '几' },
    { number: 17, radical: '凵' },
    { number: 18, radical: '刂 刁 刀' },
    { number: 19, radical: '力' },
    { number: 20, radical: '勹' },
    { number: 21, radical: '匕' },
    { number: 22, radical: '匚' },
    { number: 23, radical: '匸' },
    { number: 24, radical: '十' },
    { number: 25, radical: '卜' },
    { number: 26, radical: '卩' },
    { number: 27, radical: '厂' },
    { number: 28, radical: '厶' },
    { number: 29, radical: '又' },
    { number: 30, radical: '口' },
    { number: 31, radical: '囗' },
    { number: 32, radical: '土' },
    { number: 33, radical: '士' },
    { number: 34, radical: '夂' },
    { number: 35, radical: '夊' },
    { number: 36, radical: '夕' },
    { number: 37, radical: '大' },
    { number: 38, radical: '女' },
    { number: 39, radical: '子' },
    { number: 40, radical: '宀' },
    { number: 41, radical: '寸' },
    { number: 42, radical: '小 ⺌ ⺍' },
    { number: 43, radical: '尢' },
    { number: 44, radical: '尸' },
    { number: 45, radical: '屮' },
    { number: 46, radical: '山' },
    { number: 47, radical: '川 巛' },
    { number: 48, radical: '工' },
    { number: 49, radical: '己' },
    { number: 50, radical: '巾' },
    { number: 51, radical: '干' },
    { number: 52, radical: '幺' },
    { number: 53, radical: '广' },
    { number: 54, radical: '廴' },
    { number: 55, radical: '廾' },
    { number: 56, radical: '弋' },
    { number: 57, radical: '弓' },
    { number: 58, radical: '彐 彑' },
    { number: 59, radical: '彡' },
    { number: 60, radical: '彳' },
    { number: 61, radical: '心 忄' },
    { number: 62, radical: '戈' },
    { number: 63, radical: '戶 户' },
    { number: 64, radical: '扌' },
    { number: 65, radical: '支' },
    { number: 66, radical: '攴 攵' },
    { number: 67, radical: '文' },
    { number: 68, radical: '斗' },
    { number: 69, radical: '斤' },
    { number: 70, radical: '方' },
    { number: 71, radical: '无/旡' },
    { number: 72, radical: '日' },
    { number: 73, radical: '曰' },
    { number: 74, radical: '月' },
    { number: 75, radical: '木 朩' },
    { number: 76, radical: '欠' },
    { number: 77, radical: '止' },
    { number: 78, radical: '歹' },
    { number: 79, radical: '殳' },
    { number: 80, radical: '母' },
    { number: 81, radical: '比' },
    { number: 82, radical: '毛' },
    { number: 83, radical: '氏' },
    { number: 84, radical: '气' },
    { number: 85, radical: '水 氵 氺' },
    { number: 86, radical: '火 灬' },
    { number: 87, radical: '爪 爫' },
    { number: 88, radical: '父' },
    { number: 89, radical: '爻' },
    { number: 90, radical: '爿' },
    { number: 91, radical: '片' },
    { number: 92, radical: '牙' },
    { number: 93, radical: '牛 牜 ⺧' },
    { number: 94, radical: '犬 犭' },
    { number: 95, radical: '玄' },
    { number: 96, radical: '王 玉' },
    { number: 97, radical: '瓜' },
    { number: 98, radical: '瓦' },
    { number: 99, radical: '甘' },
    { number: 100, radical: '生' },
    { number: 101, radical: '用' },
    { number: 102, radical: '田' },
    { number: 103, radical: '疋 𤴔' },
    { number: 104, radical: '疒' },
    { number: 105, radical: '癶' },
    { number: 106, radical: '白' },
    { number: 107, radical: '皮' },
    { number: 108, radical: '皿' },
    { number: 109, radical: '目' },
    { number: 110, radical: '矛' },
    { number: 111, radical: '矢' },
    { number: 112, radical: '石' },
    { number: 113, radical: '示 礻' },
    { number: 114, radical: '禸' },
    { number: 115, radical: '禾' },
    { number: 116, radical: '穴' },
    { number: 117, radical: '立' },
    { number: 118, radical: '竹 ⺮ ケ' },
    { number: 119, radical: '米' },
    { number: 120, radical: '糸 纟' },
    { number: 121, radical: '缶' },
    { number: 122, radical: '网 罒 罓' },
    { number: 123, radical: '羊 ⺶ ⺷' },
    { number: 124, radical: '羽' },
    { number: 125, radical: '老 耂' },
    { number: 126, radical: '而' },
    { number: 127, radical: '耒' },
    { number: 128, radical: '耳' },
    { number: 129, radical: '聿' },
    { number: 130, radical: '肉 月' },
    { number: 131, radical: '臣' },
    { number: 132, radical: '自' },
    { number: 133, radical: '至' },
    { number: 134, radical: '臼' },
    { number: 135, radical: '舌' },
    { number: 136, radical: '舛' },
    { number: 137, radical: '舟' },
    { number: 138, radical: '艮' },
    { number: 139, radical: '色' },
    { number: 140, radical: '艹' },
    { number: 141, radical: '虍' },
    { number: 142, radical: '虫' },
    { number: 143, radical: '血' },
    { number: 144, radical: '行' },
    { number: 145, radical: '衣' },
  { number: 146, radical: '覀' },
  { number: 147, radical: '见' },
  { number: 148, radical: '角' },
  { number: 149, radical: '讠' },
  { number: 150, radical: '谷' },
  { number: 151, radical: '豆' },
  { number: 152, radical: '豕' },
  { number: 153, radical: '豸' },
  { number: 154, radical: '贝' },
  { number: 155, radical: '赤' },
  { number: 156, radical: '走' },
  { number: 157, radical: '足' },
  { number: 158, radical: '身' },
  { number: 159, radical: '车' },
  { number: 160, radical: '辛' },
  { number: 161, radical: '辰' },
  { number: 162, radical: '辶' },
  { number: 163, radical: '邑' },
  { number: 164, radical: '酉' },
  { number: 165, radical: '釆' },
  { number: 166, radical: '里' },
  { number: 167, radical: '金' },
  { number: 168, radical: '长' },
  { number: 169, radical: '门' },
  { number: 170, radical: '阜' },
  { number: 171, radical: '隶' },
  { number: 172, radical: '隹' },
  { number: 173, radical: '雨' },
  { number: 174, radical: '青' },
  { number: 175, radical: '非' },
  { number: 176, radical: '面' },
  { number: 177, radical: '革' },
  { number: 178, radical: '韦' },
  { number: 179, radical: '韭' },
  { number: 180, radical: '音' },
  { number: 181, radical: '页' },
  { number: 182, radical: '风' },
  { number: 183, radical: '飞' },
  { number: 184, radical: '食' },
  { number: 185, radical: '首' },
  { number: 186, radical: '香' },
  { number: 187, radical: '马' },
  { number: 188, radical: '骨' },
  { number: 189, radical: '高' },
  { number: 190, radical: '髟' },
  { number: 191, radical: '门' },
  { number: 192, radical: '鬯' },
  { number: 193, radical: '鬲' },
  { number: 194, radical: '鬼' },
  { number: 195, radical: '鱼' },
  { number: 196, radical: '鸟' },
  { number: 197, radical: '卤' },
  { number: 198, radical: '鹿' },
  { number: 199, radical: '麦' },
  { number: 200, radical: '麻' },
  { number: 201, radical: '黄' },
  { number: 202, radical: '黍' },
  { number: 203, radical: '黑' },
  { number: 204, radical: '黹' },
  { number: 205, radical: '黾' },
  { number: 206, radical: '鼎' },
  { number: 207, radical: '鼓' },
  { number: 208, radical: '鼠' },
  { number: 209, radical: '鼻' },
  { number: 210, radical: '齐' },
  { number: 211, radical: '齿' },
  { number: 212, radical: '龙' },
  { number: 213, radical: '龟' },
  { number: 214, radical: '龠' }
];

module.exports = { getRadicalNum, checksRadicals, radicals, fetchCharacters, getAllRadicals };
